[SPARK-52259][ML][CONNECT] Fix Param class binary compatibility
### What changes were proposed in this pull request?

This PR fixes the following issue:

Integrating third-party ML libraries with Spark 4.0.0 may encounter compatiblity issues due to an interface change. As an example, users may encounter the following error when using xgboost4j with Spark:
```
NoSuchMethodError: 'void org.apache.spark.ml.param.Param.<init>(org.apache.spark.ml.util.Identifiable, java.lang.String, java.lang.String)'
```

### Why are the changes needed?

Fix binary compatibility

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Manually.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #50981 from WeichenXu123/SPARK-52259.

Lead-authored-by: Weichen Xu <weichen.xu@databricks.com>
Co-authored-by: WeichenXu <weichen.xu@databricks.com>
Signed-off-by: Weichen Xu <weichen.xu@databricks.com>