[SPARK-51946][SQL] Eagerly fail for creating hive-incompatible datasource table with 'col' a partition name
### What changes were proposed in this pull request?

Eagerly fail for creating hive-incompatible datasource table with 'col' a partition name

### Why are the changes needed?

The EMPTY_DATA_SCHEMA will be treated as a partition column in HiveClientImpl, and the data schema being put in the HMS table is empty.

```
spark-sql (default)> CREATE TABLE t (col int, b TIMESTAMP_NTZ) USING json PARTITIONED BY (col)
                   > ;
25/04/29 16:17:37 WARN HiveExternalCatalog: Hive incompatible types found: timestamp_ntz. Persisting data source table `spark_catalog`.`default`.`t` into Hive metastore in Spark SQL specific format, which is NOT compatible with Hive.
25/04/29 16:17:37 WARN SessionState: METASTORE_FILTER_HOOK will be ignored, since hive.security.authorization.manager is set to instance of HiveAuthorizerFactory.
org.apache.hadoop.hive.ql.metadata.HiveException: org.apache.hadoop.hive.ql.metadata.HiveException: at least one column must be specified for the table
org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: org.apache.hadoop.hive.ql.metadata.HiveException: at least one column must be specified for the table
```

This kind of error is meaningless and misleading for users

### Does this PR introduce _any_ user-facing change?

No, the invalid case is AS-IS w/ an error message change

### How was this patch tested?
new tests

### Was this patch authored or co-authored using generative AI tooling?
no

Closes #50750 from yaooqinn/SPARK-51946.

Authored-by: Kent Yao <yao@apache.org>
Signed-off-by: Kent Yao <yao@apache.org>